// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pathfinder.CampaignManagement.Infrastructure.Data;

#nullable disable

namespace Pathfinder.CampaignManagement.Infrastructure.Migrations
{
    [DbContext(typeof(CampaignManagementDbContext))]
    [Migration("20260721133746_AddCampaignParties")]
    partial class AddCampaignParties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("campaign_management")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pathfinder.CampaignManagement.Domain.Campaigns.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Campaign", "campaign_management");
                });

            modelBuilder.Entity("Pathfinder.CampaignManagement.Domain.Campaigns.CampaignInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("InvitedUserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("CampaignId", "InvitedUserId", "Status");

                    b.ToTable("CampaignInvitation", "campaign_management");
                });

            modelBuilder.Entity("Pathfinder.CampaignManagement.Domain.Campaigns.CampaignMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CampaignId", "UserId", "Role")
                        .IsUnique();

                    b.ToTable("CampaignMembership", "campaign_management");
                });

            modelBuilder.Entity("Pathfinder.CampaignManagement.Domain.Campaigns.CampaignParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignParty", "campaign_management");
                });

            modelBuilder.Entity("Pathfinder.CampaignManagement.Domain.Campaigns.CampaignPartyCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CampaignPartyId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("ControlledByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CampaignPartyId", "CharacterId")
                        .IsUnique();

                    b.ToTable("CampaignPartyCharacter", "campaign_management");
                });

            modelBuilder.Entity("Pathfinder.CampaignManagement.Domain.Campaigns.CampaignInvitation", b =>
                {
                    b.HasOne("Pathfinder.CampaignManagement.Domain.Campaigns.Campaign", null)
                        .WithMany("Invitations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.CampaignManagement.Domain.Campaigns.CampaignMembership", b =>
                {
                    b.HasOne("Pathfinder.CampaignManagement.Domain.Campaigns.Campaign", null)
                        .WithMany("Memberships")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.CampaignManagement.Domain.Campaigns.CampaignParty", b =>
                {
                    b.HasOne("Pathfinder.CampaignManagement.Domain.Campaigns.Campaign", null)
                        .WithMany("Parties")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.CampaignManagement.Domain.Campaigns.CampaignPartyCharacter", b =>
                {
                    b.HasOne("Pathfinder.CampaignManagement.Domain.Campaigns.CampaignParty", null)
                        .WithMany("Characters")
                        .HasForeignKey("CampaignPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.CampaignManagement.Domain.Campaigns.Campaign", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Memberships");

                    b.Navigation("Parties");
                });

            modelBuilder.Entity("Pathfinder.CampaignManagement.Domain.Campaigns.CampaignParty", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
