// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pathfinder.Inventory.Infrastructure.Data;

#nullable disable

namespace Pathfinder.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260722151541_AddExchangeFinalization")]
    partial class AddExchangeFinalization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pathfinder.Inventory.Domain.Containers.InventoryContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ContainerKey")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerKind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContainerKey")
                        .IsUnique();

                    b.HasIndex("CampaignId", "ContainerKey")
                        .IsUnique();

                    b.HasIndex("CampaignId", "OwnerKind", "OwnerId")
                        .IsUnique();

                    b.ToTable("InventoryContainer", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_InventoryContainer_PositiveIds", "\"CampaignId\" > 0 AND \"OwnerId\" > 0");
                        });
                });

            modelBuilder.Entity("Pathfinder.Inventory.Domain.Items.ItemInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentContainerKey")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InstanceKey")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemConfigurationId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReservationKey")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstanceKey")
                        .IsUnique();

                    b.HasIndex("ItemConfigurationId");

                    b.HasIndex("CampaignId", "CurrentContainerKey");

                    b.ToTable("ItemInstance", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_ItemInstance_State", "\"CampaignId\" > 0 AND \"ItemConfigurationId\" > 0 AND \"Quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("Pathfinder.Inventory.Domain.Movements.InventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("FromContainerKey")
                        .HasColumnType("uuid");

                    b.Property<int>("ItemInstanceId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ItemInstanceKey")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ToContainerKey")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemInstanceId", "OperationId")
                        .IsUnique();

                    b.ToTable("InventoryMovement", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_InventoryMovement_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Pathfinder.Inventory.Domain.Operations.InventoryOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemInstanceId")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RelatedKey")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionAfter")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemInstanceId", "OperationId")
                        .IsUnique();

                    b.ToTable("InventoryOperation", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_InventoryOperation_State", "\"Quantity\" > 0 AND \"VersionAfter\" > 0");
                        });
                });

            modelBuilder.Entity("Pathfinder.Inventory.Domain.Transfers.PartyExchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CounterpartyCharacterId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExchangeKey")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FinalOperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("InitiatorCharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeKey")
                        .IsUnique();

                    b.ToTable("PartyExchange", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_PartyExchange_State", "\"CampaignId\" > 0 AND \"PartyId\" > 0 AND \"InitiatorCharacterId\" > 0 AND \"CounterpartyCharacterId\" > 0");
                        });
                });

            modelBuilder.Entity("Pathfinder.Inventory.Domain.Transfers.PartyExchangeLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpectedItemVersion")
                        .HasColumnType("integer");

                    b.Property<int>("FromCharacterId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ItemInstanceKey")
                        .HasColumnType("uuid");

                    b.Property<int>("PartyExchangeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartyExchangeId", "ItemInstanceKey")
                        .IsUnique();

                    b.ToTable("PartyExchangeLine", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_PartyExchangeLine_State", "\"FromCharacterId\" > 0 AND \"ExpectedItemVersion\" >= 0");
                        });
                });

            modelBuilder.Entity("Pathfinder.Inventory.Domain.Transfers.PartyGift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AcceptanceOperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DestinationCharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedItemVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GiftKey")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemInstanceKey")
                        .HasColumnType("uuid");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceCharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GiftKey")
                        .IsUnique();

                    b.HasIndex("ItemInstanceKey");

                    b.HasIndex("CampaignId", "PartyId", "Status");

                    b.ToTable("PartyGift", "inventory", t =>
                        {
                            t.HasCheckConstraint("CK_PartyGift_State", "\"CampaignId\" > 0 AND \"PartyId\" > 0 AND \"SourceCharacterId\" > 0 AND \"DestinationCharacterId\" > 0 AND \"ExpectedItemVersion\" >= 0");
                        });
                });

            modelBuilder.Entity("Pathfinder.Inventory.Domain.Items.ItemInstance", b =>
                {
                    b.HasOne("Pathfinder.Inventory.Domain.Containers.InventoryContainer", null)
                        .WithMany()
                        .HasForeignKey("CampaignId", "CurrentContainerKey")
                        .HasPrincipalKey("CampaignId", "ContainerKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.Inventory.Domain.Movements.InventoryMovement", b =>
                {
                    b.HasOne("Pathfinder.Inventory.Domain.Items.ItemInstance", null)
                        .WithMany("Movements")
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.Inventory.Domain.Operations.InventoryOperation", b =>
                {
                    b.HasOne("Pathfinder.Inventory.Domain.Items.ItemInstance", null)
                        .WithMany("Operations")
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.Inventory.Domain.Transfers.PartyExchangeLine", b =>
                {
                    b.HasOne("Pathfinder.Inventory.Domain.Transfers.PartyExchange", null)
                        .WithMany("Lines")
                        .HasForeignKey("PartyExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.Inventory.Domain.Items.ItemInstance", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("Operations");
                });

            modelBuilder.Entity("Pathfinder.Inventory.Domain.Transfers.PartyExchange", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
