// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pathfinder.ItemCatalog.Infrastructure.Data;

#nullable disable

namespace Pathfinder.ItemCatalog.Infrastructure.Migrations
{
    [DbContext(typeof(ItemCatalogDbContext))]
    [Migration("20260722100809_AddTypedRuleComponents")]
    partial class AddTypedRuleComponents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("item_catalog")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Items.ItemDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ItemDefinition", "item_catalog");
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Items.ItemRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bulk")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("ItemDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PriceInCopperPieces")
                        .HasColumnType("integer");

                    b.Property<int>("PrimaryCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(9);

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemDefinitionId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("ItemRevision", "item_catalog");
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.ArmorComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmorClassBonus")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("CheckPenalty")
                        .HasColumnType("integer");

                    b.Property<int>("DexterityCap")
                        .HasColumnType("integer");

                    b.Property<int>("ItemRevisionId")
                        .HasColumnType("integer");

                    b.Property<int>("SpeedPenaltyFeet")
                        .HasColumnType("integer");

                    b.Property<int>("StrengthRequirement")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemRevisionId")
                        .IsUnique();

                    b.ToTable("ArmorComponent", "item_catalog");
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.AttackComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DamageDieCount")
                        .HasColumnType("integer");

                    b.Property<int>("DamageDieSize")
                        .HasColumnType("integer");

                    b.Property<int>("DamageType")
                        .HasColumnType("integer");

                    b.Property<int>("Hands")
                        .HasColumnType("integer");

                    b.Property<int>("ItemRevisionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RangeIncrementFeet")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemRevisionId");

                    b.ToTable("AttackComponent", "item_catalog");
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.ChargeComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultActivationCost")
                        .HasColumnType("integer");

                    b.Property<int>("ItemRevisionId")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumCharges")
                        .HasColumnType("integer");

                    b.Property<int>("RecoveryRule")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemRevisionId")
                        .IsUnique();

                    b.ToTable("ChargeComponent", "item_catalog");
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.ConsumptionComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemRevisionId")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemRevisionId")
                        .IsUnique();

                    b.ToTable("ConsumptionComponent", "item_catalog");
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.DurabilityComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokenThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("Hardness")
                        .HasColumnType("integer");

                    b.Property<int>("ItemRevisionId")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumHitPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemRevisionId")
                        .IsUnique();

                    b.ToTable("DurabilityComponent", "item_catalog");
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.EquipmentComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemRevisionId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredHands")
                        .HasColumnType("integer");

                    b.Property<int>("Usage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemRevisionId")
                        .IsUnique();

                    b.ToTable("EquipmentComponent", "item_catalog");
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.ShieldComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemRevisionId")
                        .HasColumnType("integer");

                    b.Property<int>("RaisedArmorClassBonus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemRevisionId")
                        .IsUnique();

                    b.ToTable("ShieldComponent", "item_catalog");
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Items.ItemRevision", b =>
                {
                    b.HasOne("Pathfinder.ItemCatalog.Domain.Items.ItemDefinition", null)
                        .WithMany("Revisions")
                        .HasForeignKey("ItemDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.ArmorComponent", b =>
                {
                    b.HasOne("Pathfinder.ItemCatalog.Domain.Items.ItemRevision", null)
                        .WithOne("Armor")
                        .HasForeignKey("Pathfinder.ItemCatalog.Domain.Rules.ArmorComponent", "ItemRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.AttackComponent", b =>
                {
                    b.HasOne("Pathfinder.ItemCatalog.Domain.Items.ItemRevision", null)
                        .WithMany("Attacks")
                        .HasForeignKey("ItemRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.ChargeComponent", b =>
                {
                    b.HasOne("Pathfinder.ItemCatalog.Domain.Items.ItemRevision", null)
                        .WithOne("Charges")
                        .HasForeignKey("Pathfinder.ItemCatalog.Domain.Rules.ChargeComponent", "ItemRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.ConsumptionComponent", b =>
                {
                    b.HasOne("Pathfinder.ItemCatalog.Domain.Items.ItemRevision", null)
                        .WithOne("Consumption")
                        .HasForeignKey("Pathfinder.ItemCatalog.Domain.Rules.ConsumptionComponent", "ItemRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.DurabilityComponent", b =>
                {
                    b.HasOne("Pathfinder.ItemCatalog.Domain.Items.ItemRevision", null)
                        .WithOne("Durability")
                        .HasForeignKey("Pathfinder.ItemCatalog.Domain.Rules.DurabilityComponent", "ItemRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.EquipmentComponent", b =>
                {
                    b.HasOne("Pathfinder.ItemCatalog.Domain.Items.ItemRevision", null)
                        .WithOne("Equipment")
                        .HasForeignKey("Pathfinder.ItemCatalog.Domain.Rules.EquipmentComponent", "ItemRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Rules.ShieldComponent", b =>
                {
                    b.HasOne("Pathfinder.ItemCatalog.Domain.Items.ItemRevision", null)
                        .WithOne("Shield")
                        .HasForeignKey("Pathfinder.ItemCatalog.Domain.Rules.ShieldComponent", "ItemRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Items.ItemDefinition", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Pathfinder.ItemCatalog.Domain.Items.ItemRevision", b =>
                {
                    b.Navigation("Armor");

                    b.Navigation("Attacks");

                    b.Navigation("Charges");

                    b.Navigation("Consumption");

                    b.Navigation("Durability");

                    b.Navigation("Equipment");

                    b.Navigation("Shield");
                });
#pragma warning restore 612, 618
        }
    }
}
