// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pathfinder.CharacterManagement.Infrastructure.Data;

#nullable disable

namespace Pathfinder.CharacterManagement.Infrastructure.Migrations
{
    [DbContext(typeof(CharacterManagementDbContext))]
    [Migration("20260714161612_AddBardMuse")]
    partial class AddBardMuse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("character_management")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pathfinder.CharacterManagement.Domain.Entity.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 3L, null, null, null, null, null);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Account", "character_management");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "System",
                            Surname = "Administrator",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Test",
                            Surname = "User",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Pathfinder.CharacterManagement.Domain.Entity.DraftCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("AncestryType")
                        .HasColumnType("integer");

                    b.Property<string>("AppliedFinalFreeBoosts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("AppliedFreeBoosts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Concept")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SelectedAncestryFeatId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SelectedBackgroundFreeBoost")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedBackgroundId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SelectedBackgroundRestrictedBoost")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedBardMuseId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SelectedClassId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SelectedClassKeyAbility")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedClericDoctrineId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SelectedDeityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SelectedDivineFont")
                        .HasColumnType("integer");

                    b.Property<int?>("SelectedDivineSanctification")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedDruidicOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SelectedHeritageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SelectedHuntersEdgeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SelectedRogueRacketId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TrainedLore")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("TrainedSkills")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Character", "character_management");
                });

            modelBuilder.Entity("Pathfinder.CharacterManagement.Domain.Entity.DraftCharacter", b =>
                {
                    b.HasOne("Pathfinder.CharacterManagement.Domain.Entity.Account", "Account")
                        .WithMany("DraftCharacters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Pathfinder.CharacterManagement.Domain.Entity.AbilityScores", "AbilityScores", b1 =>
                        {
                            b1.Property<int>("DraftCharacterId")
                                .HasColumnType("integer");

                            b1.HasKey("DraftCharacterId");

                            b1.ToTable("Character", "character_management");

                            b1.WithOwner()
                                .HasForeignKey("DraftCharacterId");

                            b1.OwnsOne("Pathfinder.CharacterManagement.Domain.Entity.Characteristic", "Charisma", b2 =>
                                {
                                    b2.Property<int>("AbilityScoresDraftCharacterId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("Cha");

                                    b2.HasKey("AbilityScoresDraftCharacterId");

                                    b2.ToTable("Character", "character_management");

                                    b2.WithOwner()
                                        .HasForeignKey("AbilityScoresDraftCharacterId");
                                });

                            b1.OwnsOne("Pathfinder.CharacterManagement.Domain.Entity.Characteristic", "Constitution", b2 =>
                                {
                                    b2.Property<int>("AbilityScoresDraftCharacterId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("Con");

                                    b2.HasKey("AbilityScoresDraftCharacterId");

                                    b2.ToTable("Character", "character_management");

                                    b2.WithOwner()
                                        .HasForeignKey("AbilityScoresDraftCharacterId");
                                });

                            b1.OwnsOne("Pathfinder.CharacterManagement.Domain.Entity.Characteristic", "Dexterity", b2 =>
                                {
                                    b2.Property<int>("AbilityScoresDraftCharacterId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("Dex");

                                    b2.HasKey("AbilityScoresDraftCharacterId");

                                    b2.ToTable("Character", "character_management");

                                    b2.WithOwner()
                                        .HasForeignKey("AbilityScoresDraftCharacterId");
                                });

                            b1.OwnsOne("Pathfinder.CharacterManagement.Domain.Entity.Characteristic", "Intelligence", b2 =>
                                {
                                    b2.Property<int>("AbilityScoresDraftCharacterId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("Int");

                                    b2.HasKey("AbilityScoresDraftCharacterId");

                                    b2.ToTable("Character", "character_management");

                                    b2.WithOwner()
                                        .HasForeignKey("AbilityScoresDraftCharacterId");
                                });

                            b1.OwnsOne("Pathfinder.CharacterManagement.Domain.Entity.Characteristic", "Strength", b2 =>
                                {
                                    b2.Property<int>("AbilityScoresDraftCharacterId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("Str");

                                    b2.HasKey("AbilityScoresDraftCharacterId");

                                    b2.ToTable("Character", "character_management");

                                    b2.WithOwner()
                                        .HasForeignKey("AbilityScoresDraftCharacterId");
                                });

                            b1.OwnsOne("Pathfinder.CharacterManagement.Domain.Entity.Characteristic", "Wisdom", b2 =>
                                {
                                    b2.Property<int>("AbilityScoresDraftCharacterId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("Wis");

                                    b2.HasKey("AbilityScoresDraftCharacterId");

                                    b2.ToTable("Character", "character_management");

                                    b2.WithOwner()
                                        .HasForeignKey("AbilityScoresDraftCharacterId");
                                });

                            b1.Navigation("Charisma")
                                .IsRequired();

                            b1.Navigation("Constitution")
                                .IsRequired();

                            b1.Navigation("Dexterity")
                                .IsRequired();

                            b1.Navigation("Intelligence")
                                .IsRequired();

                            b1.Navigation("Strength")
                                .IsRequired();

                            b1.Navigation("Wisdom")
                                .IsRequired();
                        });

                    b.Navigation("AbilityScores")
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Pathfinder.CharacterManagement.Domain.Entity.Account", b =>
                {
                    b.Navigation("DraftCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
