export const messages = {
  ru: {
    app: {
      productName: 'Pathfinder', productSubtitle: 'Лист персонажа', language: 'Язык', languageNames: { ru: 'Русский', en: 'Английский' },
      navigation: { characters: 'Персонажи', createCharacter: 'Создать персонажа' },
      auth: { signIn: 'Войти', signOut: 'Выйти' },
    },
    routes: { characters: 'Мои персонажи', login: 'Вход', register: 'Регистрация', characterDetails: 'Персонаж', characterCreate: 'Создание персонажа', notFound: 'Страница не найдена' },
    common: { cancel: 'Отмена', back: 'Назад', next: 'Далее', retry: 'Повторить', open: 'Открыть', delete: 'Удалить', details: 'Детали', character: 'Персонаж', name: 'Имя' },
    errors: { connection: 'Не удалось подключиться к серверу. Повторите попытку позже.', request: 'Не удалось выполнить запрос. Повторите попытку позже.', invalidCredentials: 'Неверный логин или пароль.', passwordsMismatch: 'Пароли не совпадают.' },
    auth: { ledger: 'Лист персонажа', welcome: 'С возвращением', signInPrompt: 'Войдите, чтобы продолжить приключение.', userNameOrEmail: 'Никнейм или эл. почта', password: 'Пароль', noAccount: 'Нет аккаунта?', register: 'Зарегистрироваться', createAccount: 'Создайте аккаунт', registrationPrompt: 'Он понадобится для сохранения персонажей.', userName: 'Никнейм', email: 'Электронная почта', firstName: 'Имя', surname: 'Фамилия', passwordRepeat: 'Повтор пароля', hasAccount: 'Уже есть аккаунт?' },
    dashboard: { eyebrow: 'Ваше приключение', lead: 'Соберите историю героя, сохраните его выборы и возвращайтесь к игре без лишних таблиц.', emptyTitle: 'Первый герой ждёт вас', emptyText: 'Создайте персонажа, чтобы начать вести его историю.' },
    characters: { title: 'Мои персонажи', ancestry: 'Родословная', abilities: 'Характеристики', ancestryPackage: 'Пакет родословной', backgroundPackage: 'Предыстория', backgroundBoosts: 'Бусты предыстории', backgroundGrants: 'Навыки и талант', training: 'Обучение навыкам', trainedSkills: 'Освоенные навыки', trainedLore: 'Освоенные знания', heritage: 'Наследие', ancestryFeat: 'Талант родословной', vision: 'Зрение', baseHitPoints: 'Базовые HP', maximumHitPoints: 'Максимум HP', hitPointsValue: '{value} HP', hitPointsAncestry: 'Родословная', hitPointsClass: 'Класс', hitPointsConstitution: 'Модификатор Выносливости', languages: 'Языки', finalFreeBoosts: 'Финальные свободные бусты', noConcept: 'История ещё не написана.', age: 'Возраст: {age}', ageUnknown: 'Возраст не указан', deleteTitle: 'Удалить персонажа?', deleteText: 'Это действие нельзя отменить.' },
    wizard: { eyebrow: 'Новый герой', title: 'Создание персонажа', lead: 'Сервер применит правила родословной, предыстории и класса и рассчитает итоговые характеристики.', loading: 'Загружаем родословные…', loadingCatalogs: 'Загружаем каталоги…', basic: 'Основное', ancestry: 'Родословная', choices: 'Наследие и талант', boosts: 'Бусты', background: 'Предыстория', finalFreeBoosts: 'Финальные бусты', finalFreeBoostsHint: 'Выберите четыре разные характеристики. Выбрано: {selected} из 4.', finalBoostScore: '{before} → {after}', review: 'Проверка', name: 'Имя персонажа', nameRequired: 'Укажите имя', concept: 'Краткая концепция', conceptHint: 'Кем является ваш персонаж?', age: 'Возраст', ancestryHint: 'Выберите происхождение героя. Его правила определит сервер.', choicesHint: 'Выберите одно наследие и один талант первого уровня.', backgroundHint: 'Предыстория даёт бусты, обучение одному навыку и одному виду знаний.', backgroundRestrictedBoost: 'Буст предыстории', backgroundFreeBoost: 'Свободный буст предыстории', backgroundBoosts: 'Бусты предыстории', backgroundGrants: 'Навыки и талант', backgroundTraining: 'Обучение от предыстории', deferredFeat: 'Талант будет применён после добавления подсистемы талантов.', deferredChoice: 'Выбор будет доступен после добавления системы навыков.', heritage: 'Наследие', ancestryFeat: 'Талант родословной', speed: 'скорость {speed}', fixedBoosts: '{count} фикс. буста', freeBoostsHint: 'Выберите {count}: {kind}. Фиксированные бусты: {boosts}.', oneAbility: 'характеристику', severalAbilities: 'разные характеристики', none: 'нет', selectedAncestry: 'Родословная', selectedBoosts: 'Свободные бусты', selectedConcept: 'Концепция', resultHint: 'Итоговые характеристики рассчитывает сервер после создания.', create: 'Создать персонажа' },
    classUi: {
      characterClass: 'Класс', package: 'Пакет класса', hint: 'Выберите класс и одну доступную ключевую характеристику.', baseHitPoints: 'HP класса', keyAbility: 'Ключевая характеристика', initialProficiencies: 'Стартовые владения', rules: 'Правила класса', deferredChoice: 'Фактический выбор будет доступен после добавления соответствующей подсистемы.',
      names: { bard: 'Бард', cleric: 'Жрец', druid: 'Друид', fighter: 'Воин', ranger: 'Следопыт', rogue: 'Плут', witch: 'Ведьма', wizard: 'Волшебник' },
    },
    proficiencies: {
      categories: { Perception: 'Восприятие', SavingThrow: 'Спасброски', Attack: 'Атаки', Defense: 'Защита', ClassDc: 'КС класса' },
      ranks: { Untrained: 'без подготовки', Trained: 'обучен', Expert: 'эксперт', Master: 'мастер', Legendary: 'легенда' },
    },
    notFound: { title: 'Эта страница не найдена', subtitle: 'Вернитесь к списку персонажей.' },
    domain: { ancestry: { Gnome: 'Гном', Goblin: 'Гоблин', Dwarf: 'Дварф', Halfling: 'Полурослик', Human: 'Человек', Elf: 'Эльф' }, background: {
      acolyte: 'Послушник', acrobat: 'Акробат', animal_whisperer: 'Друг животных', artisan: 'Ремесленник', artist: 'Художник', barkeep: 'Трактирщик', barrister: 'Адвокат', bounty_hunter: 'Охотник за головами', charlatan: 'Шарлатан', criminal: 'Преступник', detective: 'Сыщик', emissary: 'Посланник', entertainer: 'Артист', farmhand: 'Батрак', field_medic: 'Полевой медик', fortune_teller: 'Предсказатель', gambler: 'Игрок', gladiator: 'Гладиатор', guard: 'Стражник', herbalist: 'Травник', hermit: 'Отшельник', hunter: 'Охотник', laborer: 'Рабочий', merchant: 'Торговец', martial_disciple: 'Ученик боевых искусств', miner: 'Шахтёр', nomad: 'Кочевник', noble: 'Дворянин', prisoner: 'Узник', sailor: 'Моряк', scholar: 'Учёный', scout: 'Разведчик', street_urchin: 'Беспризорник', tinker: 'Мастеровой', warrior: 'Воин',
    }, ancestryChoice: {
      dwarf_ancient_blooded: 'Дварф древней крови', dwarf_death_warden: 'Страж смерти', dwarf_forge: 'Кузнечный дварф', dwarf_rock: 'Каменный дварф', dwarf_strong_blooded: 'Дварф крепкой крови', dwarf_dwarven_doughtiness: 'Дварфская стойкость', dwarf_dwarven_lore: 'Знания дварфов', dwarf_dwarven_weapon_familiarity: 'Знакомство с оружием дварфов', dwarf_mountain_strategy: 'Горная стратегия', dwarf_rock_runner: 'Бегун по камням', dwarf_stonemasons_eye: 'Глаз каменотёса', dwarf_unburdened_iron: 'Ненагруженное железо',
      elf_ancient: 'Древний эльф', elf_arctic: 'Арктический эльф', elf_cavern: 'Пещерный эльф', elf_seer: 'Эльф-провидец', elf_whisper: 'Шепчущий эльф', elf_woodland: 'Лесной эльф', elf_ancestral_longevity: 'Наследная долговечность', elf_elven_lore: 'Знания эльфов', elf_elven_weapon_familiarity: 'Знакомство с оружием эльфов', elf_forlorn: 'Одинокий', elf_nimble_elf: 'Проворный эльф', elf_otherworldly_magic: 'Потусторонняя магия', elf_unwavering_mien: 'Непоколебимый вид',
      gnome_chameleon: 'Гном-хамелеон', gnome_fey_touched: 'Коснувшийся фей гном', gnome_sensate: 'Чуткий гном', gnome_umbral: 'Сумеречный гном', gnome_wellspring: 'Гном источника', gnome_animal_accomplice: 'Зверь-спутник', gnome_animal_elocutionist: 'Говорящий со зверями', gnome_fey_fellowship: 'Дружба с фей', gnome_first_world_magic: 'Магия Первого мира', gnome_gnome_obsession: 'Гномья одержимость', gnome_gnome_weapon_familiarity: 'Знакомство с оружием гномов', gnome_razzle_dazzle: 'Блеск и мишура',
      goblin_charhide: 'Углекожий гоблин', goblin_irongut: 'Гоблин с железным желудком', goblin_razortooth: 'Острозубый гоблин', goblin_snow: 'Снежный гоблин', goblin_unbreakable: 'Несокрушимый гоблин', goblin_burn_it: 'Поддай жару!', goblin_goblin_lore: 'Знания гоблинов', goblin_goblin_scuttle: 'Гоблинская перебежка', goblin_goblin_song: 'Гоблинская песня', goblin_goblin_weapon_familiarity: 'Знакомство с оружием гоблинов', goblin_rough_rider: 'Лихой наездник', goblin_very_sneaky: 'Очень скрытный',
      halfling_gutsy: 'Отважный полурослик', halfling_hillock: 'Холмовой полурослик', halfling_jinxed: 'Проклятый полурослик', halfling_nomadic: 'Кочевой полурослик', halfling_twilight: 'Сумеречный полурослик', halfling_wildwood: 'Лесной полурослик', halfling_distracting_shadows: 'Отвлекающие тени', halfling_halfling_lore: 'Знания полуросликов', halfling_halfling_luck: 'Удача полурослика', halfling_halfling_weapon_familiarity: 'Знакомство с оружием полуросликов', halfling_prairie_rider: 'Наездник прерий', halfling_sure_feet: 'Твёрдая поступь',
      human_skilled: 'Умелый человек', human_versatile: 'Разносторонний человек', human_adapted_cantrip: 'Адаптированный заговор', human_cooperative_nature: 'Склонность к сотрудничеству', human_general_training: 'Общая подготовка', human_natural_ambition: 'Природное стремление', human_natural_skill: 'Природный талант', human_unconventional_weaponry: 'Необычное оружие',
    }, vision: { None: 'Обычное зрение', LowLight: 'Сумеречное зрение', Darkvision: 'Тёмное зрение' }, language: { common: 'Всеобщий', dwarven: 'Дварфийский', elven: 'Эльфийский', gnomish: 'Гномий', goblin: 'Гоблинский', halfling: 'Язык полуросликов', fey: 'Фейский', draconic: 'Драконий', empyrean: 'Эмпирейский', kholo: 'Кхолийский', orcish: 'Орочий', jotun: 'Йотунский', petran: 'Петранский', sakvroth: 'Саквротский' }, ability: { Strength: 'Сила', Dexterity: 'Ловкость', Constitution: 'Выносливость', Intelligence: 'Интеллект', Wisdom: 'Мудрость', Charisma: 'Харизма' } },
  },
  en: {
    app: {
      productName: 'Pathfinder', productSubtitle: 'Character Ledger', language: 'Language', languageNames: { ru: 'Russian', en: 'English' },
      navigation: { characters: 'Characters', createCharacter: 'Create character' },
      auth: { signIn: 'Sign in', signOut: 'Sign out' },
    },
    routes: { characters: 'My characters', login: 'Sign in', register: 'Register', characterDetails: 'Character', characterCreate: 'Create character', notFound: 'Page not found' },
    common: { cancel: 'Cancel', back: 'Back', next: 'Next', retry: 'Retry', open: 'Open', delete: 'Delete', details: 'Details', character: 'Character', name: 'Name' },
    errors: { connection: 'Unable to connect to the server. Please try again later.', request: 'Unable to complete the request. Please try again later.', invalidCredentials: 'Invalid username or password.', passwordsMismatch: 'Passwords do not match.' },
    auth: { ledger: 'Character Ledger', welcome: 'Welcome back', signInPrompt: 'Sign in to continue your adventure.', userNameOrEmail: 'Username or email', password: 'Password', noAccount: 'No account?', register: 'Register', createAccount: 'Create an account', registrationPrompt: 'You need one to save your characters.', userName: 'Username', email: 'Email address', firstName: 'First name', surname: 'Last name', passwordRepeat: 'Repeat password', hasAccount: 'Already have an account?' },
    dashboard: { eyebrow: 'Your adventure', lead: 'Build your hero’s story, save their choices, and return to the game without extra tables.', emptyTitle: 'Your first hero awaits', emptyText: 'Create a character to begin their story.' },
    characters: { title: 'My characters', ancestry: 'Ancestry', abilities: 'Abilities', ancestryPackage: 'Ancestry package', backgroundPackage: 'Background', backgroundBoosts: 'Background boosts', backgroundGrants: 'Skills and feat', training: 'Skill training', trainedSkills: 'Trained skills', trainedLore: 'Trained Lore', heritage: 'Heritage', ancestryFeat: 'Ancestry feat', vision: 'Vision', baseHitPoints: 'Base HP', maximumHitPoints: 'Maximum HP', hitPointsValue: '{value} HP', hitPointsAncestry: 'Ancestry', hitPointsClass: 'Class', hitPointsConstitution: 'Constitution modifier', languages: 'Languages', finalFreeBoosts: 'Final free boosts', noConcept: 'No character story yet.', age: 'Age: {age}', ageUnknown: 'Age is not specified', deleteTitle: 'Delete character?', deleteText: 'This action cannot be undone.' },
    wizard: { eyebrow: 'New hero', title: 'Create character', lead: 'The server will apply ancestry, background, and class rules and calculate final ability scores.', loading: 'Loading ancestries…', loadingCatalogs: 'Loading catalogs…', basic: 'Basics', ancestry: 'Ancestry', choices: 'Heritage and feat', boosts: 'Boosts', background: 'Background', finalFreeBoosts: 'Final boosts', finalFreeBoostsHint: 'Choose four different abilities. Selected: {selected} of 4.', finalBoostScore: '{before} → {after}', review: 'Review', name: 'Character name', nameRequired: 'Enter a name', concept: 'Brief concept', conceptHint: 'Who is your character?', age: 'Age', ancestryHint: 'Choose the character’s ancestry. The server determines its rules.', choicesHint: 'Choose one heritage and one 1st-level ancestry feat.', backgroundHint: 'A background grants boosts, training in one skill, and training in one Lore.', backgroundRestrictedBoost: 'Background boost', backgroundFreeBoost: 'Free background boost', backgroundBoosts: 'Background boosts', backgroundGrants: 'Skills and feat', backgroundTraining: 'Background training', deferredFeat: 'The feat will be applied after the feat subsystem is added.', deferredChoice: 'This choice will become available with the skill system.', heritage: 'Heritage', ancestryFeat: 'Ancestry feat', speed: 'speed {speed}', fixedBoosts: '{count} fixed boosts', freeBoostsHint: 'Choose {count}: {kind}. Fixed boosts: {boosts}.', oneAbility: 'an ability', severalAbilities: 'different abilities', none: 'none', selectedAncestry: 'Ancestry', selectedBoosts: 'Free boosts', selectedConcept: 'Concept', resultHint: 'The server calculates final ability scores after creation.', create: 'Create character' },
    classUi: {
      characterClass: 'Class', package: 'Class package', hint: 'Choose a class and one available key ability.', baseHitPoints: 'Class HP', keyAbility: 'Key ability', initialProficiencies: 'Initial proficiencies', rules: 'Class rules', deferredChoice: 'The actual choice will become available with the corresponding subsystem.',
      names: { bard: 'Bard', cleric: 'Cleric', druid: 'Druid', fighter: 'Fighter', ranger: 'Ranger', rogue: 'Rogue', witch: 'Witch', wizard: 'Wizard' },
    },
    proficiencies: {
      categories: { Perception: 'Perception', SavingThrow: 'Saving throws', Attack: 'Attacks', Defense: 'Defenses', ClassDc: 'Class DC' },
      ranks: { Untrained: 'untrained', Trained: 'trained', Expert: 'expert', Master: 'master', Legendary: 'legendary' },
    },
    notFound: { title: 'This page was not found', subtitle: 'Return to the character list.' },
    domain: { ancestry: { Gnome: 'Gnome', Goblin: 'Goblin', Dwarf: 'Dwarf', Halfling: 'Halfling', Human: 'Human', Elf: 'Elf' }, ability: { Strength: 'Strength', Dexterity: 'Dexterity', Constitution: 'Constitution', Intelligence: 'Intelligence', Wisdom: 'Wisdom', Charisma: 'Charisma' } },
  },
} as const
