// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pathfinder.Commerce.Infrastructure.Data;

#nullable disable

namespace Pathfinder.Commerce.Infrastructure.Migrations
{
    [DbContext(typeof(CommerceDbContext))]
    [Migration("20260723073150_AddManualShopOffers")]
    partial class AddManualShopOffers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("commerce")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pathfinder.Commerce.Domain.Offers.ShopOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ItemConfigurationId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ItemInstanceKey")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("OfferKey")
                        .HasColumnType("uuid");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("UnitPriceCopper")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemInstanceKey")
                        .IsUnique()
                        .HasFilter("\"Status\" = 1 AND \"ItemInstanceKey\" IS NOT NULL");

                    b.HasIndex("OfferKey")
                        .IsUnique();

                    b.HasIndex("ShopId");

                    b.HasIndex("CampaignId", "ShopId", "Status");

                    b.ToTable("ShopOffer", "commerce", t =>
                        {
                            t.HasCheckConstraint("CK_ShopOffer_Identity", "\"CampaignId\" > 0 AND \"ShopId\" > 0");

                            t.HasCheckConstraint("CK_ShopOffer_QuantityPrice", "\"AvailableQuantity\" > 0 AND \"UnitPriceCopper\" >= 0");

                            t.HasCheckConstraint("CK_ShopOffer_Target", "(\"Kind\" = 1 AND \"ItemConfigurationId\" IS NOT NULL AND \"ItemInstanceKey\" IS NULL) OR (\"Kind\" = 2 AND \"ItemConfigurationId\" IS NULL AND \"ItemInstanceKey\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Pathfinder.Commerce.Domain.Shops.Settlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Traits")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Name")
                        .IsUnique();

                    b.ToTable("Settlement", "commerce", t =>
                        {
                            t.HasCheckConstraint("CK_Settlement_CampaignId", "\"CampaignId\" > 0");

                            t.HasCheckConstraint("CK_Settlement_Level", "(\"Level\" >= 0) AND (\"Level\" <= 20)");
                        });
                });

            modelBuilder.Entity("Pathfinder.Commerce.Domain.Shops.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SettlementId")
                        .HasColumnType("integer");

                    b.Property<int>("ShopLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Id");

                    b.HasIndex("SettlementId", "Name")
                        .IsUnique();

                    b.ToTable("Shop", "commerce", t =>
                        {
                            t.HasCheckConstraint("CK_Shop_CampaignId", "\"CampaignId\" > 0");

                            t.HasCheckConstraint("CK_Shop_Level", "(\"ShopLevel\" >= 0) AND (\"ShopLevel\" <= 20)");
                        });
                });

            modelBuilder.Entity("Pathfinder.Commerce.Domain.Offers.ShopOffer", b =>
                {
                    b.HasOne("Pathfinder.Commerce.Domain.Shops.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.Commerce.Domain.Shops.Shop", b =>
                {
                    b.HasOne("Pathfinder.Commerce.Domain.Shops.Settlement", null)
                        .WithMany("Shops")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pathfinder.Commerce.Domain.Shops.Settlement", b =>
                {
                    b.Navigation("Shops");
                });
#pragma warning restore 612, 618
        }
    }
}
